# Generated by Django 4.2.7 on 2024-01-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='unique_id',
            field=models.CharField(default='0a2c1a09b8f641e8842f36429046f881'),
        ),
    ]
