# Generated by Django 4.2.7 on 2024-02-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customeruser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='unique_id',
            field=models.CharField(default='7e44d4ab37ae4cdfaaf2f681d3fc8a14'),
        ),
    ]
