# Generated by Django 4.2.7 on 2023-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customeruser_city_remove_customeruser_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
