# Generated by Django 4.2.7 on 2024-02-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customeruser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='unique_id',
            field=models.CharField(default='6fd58699691e4ce68a80bafdc9045a76'),
        ),
    ]
