# Generated by Django 4.2.7 on 2023-12-11 05:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_remove_customeruser_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_verified_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_verified_mobile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='verified_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='verified_mobile_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[users.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[users.models.validate_mobile]),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customUser_set', related_query_name='user', to='auth.permission'),
        ),
    ]
