# Generated by Django 4.2.7 on 2024-02-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customeruser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='unique_id',
            field=models.CharField(default='f078c57087144927ba00760cd770bc1c'),
        ),
    ]
