# Generated by Django 4.2.7 on 2023-12-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customeruser_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_verified_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
