# Generated by Django 4.2.7 on 2024-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customeruser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='unique_id',
            field=models.CharField(default='ddfa60d97ec8410ab910f1a18b9b9bdf'),
        ),
    ]
