# Generated by Django 4.2.7 on 2024-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customeruser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='unique_id',
            field=models.CharField(default='dcdaba296dab4570ab18d775c3ac517c'),
        ),
    ]
