# Generated by Django 4.2.7 on 2024-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customeruser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='unique_id',
            field=models.CharField(default='3473a752203e4ac3b716ab1457fd461c'),
        ),
    ]
