# Generated by Django 4.2.7 on 2023-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
