# Generated by Django 4.2.7 on 2023-12-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_address_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_main_address',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
