# Generated by Django 4.2.7 on 2023-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_address_is_main_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='point',
            new_name='location',
        ),
        migrations.AddField(
            model_name='address',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
