# Generated by Django 4.2.7 on 2023-12-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='users.customeruser'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='core.hashtag'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.states'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by', to='users.customeruser'),
        ),
    ]
