# Generated by Django 4.2.7 on 2023-12-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='uploaded_by',
            new_name='updated_by',
        ),
        migrations.RemoveField(
            model_name='basemodel',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
