# Generated by Django 4.2.7 on 2023-12-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_city_latitude_remove_city_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='point',
            new_name='location',
        ),
    ]
