# Generated by Django 4.2.7 on 2024-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_useravatar_avatar'),
        ('post', '0003_alter_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, related_name='post', to='albums.media'),
        ),
    ]
