# Generated by Django 4.2.7 on 2023-12-31 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('post', '0004_post_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='hashtags',
        ),
        migrations.CreateModel(
            name='CommentHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hashtag')),
            ],
        ),
    ]
