# Generated by Django 4.2.7 on 2023-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('post', '0005_remove_comment_hashtags_commenthashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hashtags',
            field=models.ManyToManyField(blank=True, through='post.CommentHashtag', to='core.hashtag'),
        ),
    ]
