# Generated by Django 4.2.7 on 2024-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='post.category', verbose_name='category'),
        ),
    ]
