# Generated by Django 4.2.7 on 2024-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='internal_code',
            field=models.CharField(default=1, max_length=255, verbose_name='Internal Code'),
            preserve_default=False,
        ),
    ]
