# Generated by Django 4.2.7 on 2024-01-29 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_useravatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.FileField(default=django.utils.timezone.now, upload_to='avatar/'),
            preserve_default=False,
        ),
    ]
