# Generated by Django 4.2.7 on 2024-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_useravatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(upload_to='media/avatar/'),
        ),
    ]
