# Generated by Django 4.2.7 on 2024-04-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='roomId',
            new_name='room_id',
        ),
    ]
