# Generated by Django 4.2.7 on 2024-04-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_userseenpost'),
        ('chat', '0005_chatmessage_updated_at_chatroom_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.post'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.post'),
        ),
    ]
